### ISSUE TITLE
После правок package.json перестали импортироваться  scss во Vue проекте v1.2.2

### ISSUE THREAD

**Issue by Savelyev-Aleksey** [Stanislavsky69/vue_dadata_3#4]
```log
(node:595138) UnhandledPromiseRejectionWarning: Error: Missing "./src/assets/variabless" export in "vue-dadata-3" package
    at bail (/path/node_modules/vite/dist/node/chunks/dep-971d9e33.js:28833:8)
    at resolve (/path/node_modules/vite/dist/node/chunks/dep-971d9e33.js:28910:10)
    at resolveExports (/path/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29533:12)
    at resolveDeepImport (/patha/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29549:26)
    at tryNodeResolve (/path/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29333:20)
    at Context.resolveId (/path/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29150:28)
    at Object.resolveId (/path/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38255:55)
    at async Object.<anonymous> (/path/node_modules/vite/dist/node/chunks/dep-971d9e33.js:70977:27)
```

Проект на Vue 3 = 3.2.31
Согласно инструкции с ~ стили не подтягиваются.
```
@import "~vue-dadata-3/src/assets/variabless";
@import "~vue-dadata-3/src/assets/styles";
```
Без ~ стили успешно подгружались в версии  1.2.1
В версии 1.2.2 стили совсем перестали подгружаться.

**Comment by Stanislavsky69** [comment]
Поправил, спасибо!
